#!/usr/bin/env python3
"""
Party container — step-by-step interactive mode (dealer-free).

Reads preprocessing from MP-SPDZ Player-Data, then runs the online phase
of Π_OnlinePPML with π_MultTrunc (Section 4.1, Procedure 1).

Preprocessing is generated by MP-SPDZ's spdz2k-party.x (real OT-based
SPDZ-2k protocol) — no trusted dealer.

Online phase for multiply-then-truncate:
  1. [Δ_{z'}] = (Δ_x+δ_x)(Δ_y+δ_y) − (Δ_y+δ_y)[a] − (Δ_x+δ_x)[b] + [c] + [λ_{z'}]
  2. Open Δ_{z'}
  3. Δ_z = ⌊Δ_{z'} / 2^d⌋  (truncation!)
  4. result = Δ_z − λ_z

Each party exposes its λ shares via GET /api/lambdas so the dashboard
(input owner) can reconstruct λ and compute Δ = input + λ.
"""

import os
import sys
import json
import time
import threading
import urllib.request
import urllib.error
from http.server import HTTPServer

sys.path.insert(0, "/app")

import numpy as np
from md_ml.share import make_share_config
from md_ml.mpspdz_reader import MpSpdzReader
from md_ml.networking import Party
from md_ml.linear_algebra import (
    matrix_multiply, matrix_add, matrix_subtract,
    matrix_add_assign, matrix_subtract_assign, matrix_scalar,
)
from md_ml.dashboard import PartyState, start_api_server, _make_handler


class StepBuilder:
    def __init__(self):
        self._steps = []
        self._idx = 0
    def add(self, name, phase="online", description=""):
        self._steps.append({"name": name, "phase": phase, "description": description})
        return self
    def register(self, state):
        state.set_steps(self._steps)
    def wait(self, state):
        state.wait_for_step(self._idx)
        self._idx += 1


def main():
    my_id = int(os.environ["PARTY_ID"])
    port_base = int(os.environ.get("PORT_BASE", "7070"))
    party0_host = os.environ.get("PARTY0_HOST", "party0")
    party1_host = os.environ.get("PARTY1_HOST", "party1")
    dash_port = int(os.environ.get("DASH_PORT", "8080"))
    player_data_dir = os.environ.get("PLAYER_DATA_DIR", "/player-data")
    mpspdz_url = os.environ.get("MPSPDZ_URL", "http://localhost:5000")

    hosts = [party0_host, party1_host]
    other_id = 1 - my_id

    state = PartyState(party_id=my_id, role="party")

    # ── Extended handler with /api/lambdas and /api/deltas ──
    lambdas_store = {"ready": False, "data": None}
    lambdas_lock = threading.Lock()
    deltas_store = {"ready": False, "data": None}
    deltas_lock = threading.Lock()

    def make_extended_handler(st):
        BaseHandler = _make_handler(st)
        class ExtHandler(BaseHandler):
            def do_GET(self):
                if self.path == "/api/lambdas":
                    with lambdas_lock:
                        if lambdas_store["ready"]:
                            self._json(lambdas_store["data"])
                        else:
                            self._json({"ready": False})
                elif self.path == "/api/deltas":
                    with deltas_lock:
                        if deltas_store["ready"]:
                            self._json(deltas_store["data"])
                        else:
                            self._json({"ready": False})
                else:
                    super().do_GET()
            def do_POST(self):
                if self.path == "/api/deltas":
                    content_len = int(self.headers.get("Content-Length", 0))
                    body = self.rfile.read(content_len)
                    data = json.loads(body)
                    with deltas_lock:
                        deltas_store["ready"] = True
                        deltas_store["data"] = data
                    self._json({"ok": True})
                else:
                    super().do_POST()
        return ExtHandler

    handler = make_extended_handler(state)
    server = HTTPServer(("0.0.0.0", dash_port), handler)
    t = threading.Thread(target=server.serve_forever, daemon=True)
    t.start()
    print(f"Party {my_id} API on http://0.0.0.0:{dash_port}", flush=True)

    while True:
        # ── Wait for config (blocks until POST /api/configure) ──
        # Stores stay available until next configure arrives
        config = state.wait_for_config()

        # Reset stores now that a new computation is starting
        with lambdas_lock:
            lambdas_store["ready"] = False
            lambdas_store["data"] = None
        with deltas_lock:
            deltas_store["ready"] = False
            deltas_store["data"] = None
        dim = config["dim"]
        d_bits = config.get("d", 20)
        k = config.get("k", 64)
        size = dim * dim
        share = make_share_config(k, s=64)

        state.log(f"Phase 1 config: {dim}×{dim} matmul with d={d_bits}, k={k}", {
            "d (fractional bits)": d_bits,
            "k (ring bits)": k,
        }, level="crypto")
        state.log("Starting preprocessing — deltas will arrive later from data parties")

        # ── Define steps ──
        sb = StepBuilder()
        # Preprocessing (trigger MP-SPDZ, then read results)
        sb.add("Trigger MP-SPDZ spdz2k preprocessing", "preprocessing",
               f"POST /api/run to MP-SPDZ sidecar with k={k}, s={k}")
        sb.add("Wait for MP-SPDZ preprocessing to complete", "preprocessing",
               "Both parties jointly generate triples via OT (no trusted dealer)")
        sb.add("Read MAC key share α^i from Player-Data", "preprocessing",
               "Generated by MP-SPDZ spdz2k-party.x via OT")
        sb.add("Read [λ_A]^i, [λ_B]^i input mask shares", "preprocessing",
               "Input masks for the dashboard's matrices A and B")
        sb.add("Expose [λ_A]^i, [λ_B]^i to dashboard via /api/lambdas", "preprocessing",
               "Dashboard reconstructs λ = [λ]^0 + [λ]^1 to compute Δ = input + λ")
        sb.add("Read Beaver triple [a]^i, [b]^i, [c]^i", "preprocessing",
               f"Matrix triple: {dim}×{dim} matrices, c = a×b")
        sb.add("Compute δ_x = a − λ_A, δ_y = b − λ_B (circuit-dependent)", "preprocessing",
               "Both parties compute the same δ from their shares (public values)")
        sb.add("Read truncation masks [λ_{z'}]^i, [λ_z]^i", "preprocessing",
               "From edaBits: λ_{z'} = 2^d · λ_z + u")
        # Networking
        sb.add(f"Connect to Party {other_id}", "connecting", "")
        # Wait for deltas from data parties (via coordinator)
        sb.add("Wait for Δ_A, Δ_B from data parties", "online",
               "Data parties compute Δ = input + λ and send via coordinator")
        # Online phase
        sb.add("temp_x = Δ_A + δ_x = A + a", "online", "")
        sb.add("temp_y = Δ_B + δ_y = B + b", "online", "")
        sb.add("Matmul 1/5: temp_xy = temp_x × temp_y = (A+a)(B+b)", "online", "")
        sb.add("[Δ_{z'}]^i = [c]^i + [λ_{z'}]^i", "online",
               "Note: using [λ_{z'}] not [λ_z] — this is the π_MultTrunc difference")
        sb.add("Matmul 2/5: [Δ_{z'}]^i −= [a]^i × temp_y", "online", "")
        sb.add("Matmul 3/5: [Δ_{z'}]^i −= temp_x × [b]^i", "online", "")
        sb.add("P_0: [Δ_{z'}]^0 += temp_xy", "online", "")
        sb.add("[Δ_{z'}_mac]^i computation (5 terms)", "online", "")
        sb.add("Matmul 4/5: MAC correction (a_mac × temp_y)", "online", "")
        sb.add("Matmul 5/5: MAC correction (temp_x × b_mac)", "online", "")
        sb.add("Exchange [Δ_{z'}]^i shares", "online",
               "The ONLY communication in the multiply gate")
        sb.add("Reconstruct Δ_{z'} = Σ[Δ_{z'}]^i", "online", "")
        sb.add(f"π_MultTrunc: Δ_z = ⌊Δ_{{z'}} / 2^{d_bits}⌋ (TRUNCATION)", "online",
               f"Step 3 of Procedure 1: integer division by 2^d removes extra scaling")
        sb.add("Exchange [λ_z]^i shares", "online",
               "Note: exchanging [λ_z] not [λ_{z'}] — λ_z is the truncated mask")
        sb.add("Reconstruct λ_z = Σ[λ_z]^i", "online", "")
        sb.add("result = Δ_z − λ_z = ⌊(A·B) / 2^d⌋ (fixed-point product!)", "online",
               f"Truncation by 2^d gives the correct fixed-point result.")
        sb.add(f"Remove upper bits → result ∈ Z_{{2^{share.k_bits}}}", "online", "")

        sb.register(state)
        state.update(status="Ready — click Start")

        # ══════════════════════════════════════════════════════════════
        # PREPROCESSING: Trigger MP-SPDZ, then read Player-Data
        # ══════════════════════════════════════════════════════════════

        # Step 0: Trigger MP-SPDZ sidecar
        sb.wait(state)
        state.log(f"═══ Triggering MP-SPDZ Preprocessing ═══", level="crypto")
        state.log(f"POST {mpspdz_url}/api/run with k={k}, s={k}, dim={dim}")
        mpspdz_config = json.dumps({"k": k, "s": k, "dim": dim, "protocol": "spdz2k", "program": "bench_simple"}).encode()
        req = urllib.request.Request(
            f"{mpspdz_url}/api/run",
            data=mpspdz_config,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            resp = urllib.request.urlopen(req, timeout=10)
            state.log(f"MP-SPDZ triggered: {resp.read().decode()}")
        except Exception as e:
            state.log(f"MP-SPDZ trigger failed: {e} — will retry or use existing Player-Data", level="warn")

        # Step 1: Wait for MP-SPDZ to finish
        sb.wait(state)
        state.log("Waiting for MP-SPDZ preprocessing to complete...", level="crypto")
        while True:
            try:
                resp = urllib.request.urlopen(f"{mpspdz_url}/api/status", timeout=5)
                status = json.loads(resp.read().decode())
                phase = status.get("phase", "idle")
                if phase == "done":
                    elapsed = status.get("elapsed_ms", 0)
                    state.log(f"MP-SPDZ preprocessing complete ({elapsed}ms)", {
                        "protocol": status.get("protocol"),
                        "k_bits": status.get("k_bits"),
                        "s_bits": status.get("s_bits"),
                        "elapsed_ms": elapsed,
                    }, level="crypto")
                    break
                elif phase == "error":
                    state.log(f"MP-SPDZ error: {status.get('error', 'unknown')}", level="error")
                    break
                else:
                    state.log(f"  MP-SPDZ phase: {phase}...")
            except Exception:
                pass
            time.sleep(1)

        reader = MpSpdzReader(share, n_parties=2, party_id=my_id,
                              player_data_dir=player_data_dir,
                              n_elements=size)

        # Step 2: MAC key
        sb.wait(state)
        state.log("═══ Reading Preprocessing from Player-Data ═══", level="crypto")
        state.log(f"Player-Data directory: {reader.base_dir}")
        global_key_shr = reader.read_mac_key()
        state.log(f"MAC key share α^{my_id}", {"α^i": global_key_shr}, level="crypto")

        # Step 3: Input masks [λ_A], [λ_B]
        sb.wait(state)
        state.log("Reading input mask shares...", level="crypto")
        la_shr, la_mac = reader.read_input_masks(size, mask_offset=0)
        lb_shr, lb_mac = reader.read_input_masks(size, mask_offset=size)
        state.log(f"[λ_A]^{my_id}, [λ_B]^{my_id} read", {
            f"[λ_A]^{my_id} value": la_shr,
            f"[λ_B]^{my_id} value": lb_shr,
        }, level="crypto")

        # Step 4: Expose λ shares to dashboard
        sb.wait(state)
        state.log("Exposing [λ]^i shares to dashboard via /api/lambdas", level="crypto")
        la_str = [str(v) for v in la_shr]
        lb_str = [str(v) for v in lb_shr]
        with lambdas_lock:
            lambdas_store["ready"] = True
            lambdas_store["data"] = {
                "ready": True,
                "party_id": my_id,
                "dim": dim,
                "k_bits": k,
                "lambda_a_share": la_str,
                "lambda_b_share": lb_str,
            }
        state.log(f"[λ_A]^{my_id}, [λ_B]^{my_id} exposed via GET /api/lambdas", {
            f"[λ_A]^{my_id} (first 4)": la_str[:4],
            f"[λ_B]^{my_id} (first 4)": lb_str[:4],
            "total_elements": size,
        })

        # Step 5: Matrix Beaver triple [a], [b], [c] where c = matmul(a, b)
        sb.wait(state)
        state.log("Reading matrix Beaver triple...", level="crypto")
        a_shr, a_mac, b_shr, b_mac, c_shr, c_mac = reader.read_matrix_triple()
        state.log(f"Beaver triple [a]^{my_id}, [b]^{my_id}, [c]^{my_id}", {
            f"[a]^{my_id}": a_shr, f"[b]^{my_id}": b_shr, f"[c]^{my_id}": c_shr,
        }, level="crypto")

        # Step 6: Compute circuit-dependent δ values
        sb.wait(state)
        state.log("═══ Circuit-Dependent δ Values ═══", level="crypto")
        sm = share.semi_mask
        delta_x_shr = [(a - la) & sm for a, la in zip(a_shr, la_shr)]
        delta_y_shr = [(b - lb) & sm for b, lb in zip(b_shr, lb_shr)]
        state.log(f"δ_x^{my_id} = [a]^{my_id} − [λ_A]^{my_id}", {
            f"δ_x^{my_id}": delta_x_shr,
            f"δ_y^{my_id}": delta_y_shr,
        }, level="crypto")

        # Step 7: Truncation masks via F_edaBits
        sb.wait(state)
        state.log("Generating truncation masks via F_edaBits...", level="crypto")
        from md_ml.protocols.mult_trunc import generate_multtrunc_masks
        lz_shr, lz_mac, lzp_shr, lzp_mac, lz_bits, u_bits = generate_multtrunc_masks(
            share, d_bits, size, my_id, global_key_shr
        )
        state.log(f"π_MultTrunc masks: [λ_{{z'}}] = 2^{d_bits} · [λ_z] + [u]", {
            f"[λ_z]^{my_id}": lz_shr,
            f"[λ_{{z'}}]^{my_id}": lzp_shr,
            f"λ_z bits (first 4)": [b[:min(4, size)] for b in lz_bits[:min(3, len(lz_bits))]],
            f"u bits (first 4)": [b[:min(4, size)] for b in u_bits[:min(3, len(u_bits))]],
        }, level="crypto")

        # Step 8: Connect to other party
        sb.wait(state)
        state.log(f"Connecting to Party {other_id}...", level="info")
        t0 = time.time()
        net = Party(my_id, 2, port_base, hosts=hosts, on_event=lambda e, d: None)
        state.log(f"Connected to Party {other_id} ({(time.time()-t0)*1000:.0f} ms)")

        # Exchange δ shares to reconstruct public δ_x, δ_y
        send_dx = share.semi_to_bytes(delta_x_shr)
        send_dy = share.semi_to_bytes(delta_y_shr)
        nbytes = size * share.semi_bytes
        recv_dx = net.send_recv_concurrent(other_id, send_dx, nbytes)
        recv_dy = net.send_recv_concurrent(other_id, send_dy, nbytes)
        other_dx = share.semi_from_bytes(recv_dx, size)
        other_dy = share.semi_from_bytes(recv_dy, size)
        delta_x_pub = matrix_add(delta_x_shr, other_dx, mask=sm)
        delta_y_pub = matrix_add(delta_y_shr, other_dy, mask=sm)
        state.log("δ_x, δ_y reconstructed (public)", {
            "δ_x": delta_x_pub, "δ_y": delta_y_pub,
        }, level="crypto")

        bytes_sent = len(send_dx) + len(send_dy)
        state.update(bytes_sent=bytes_sent)

        # ══════════════════════════════════════════════════════════════
        # ONLINE PHASE (extracted to online_phase.py)
        # ══════════════════════════════════════════════════════════════
        from online_phase import run_online_phase
        result, bytes_sent = run_online_phase(
            sb=sb, state=state, share=share, net=net,
            my_id=my_id, other_id=other_id, dim=dim, d_bits=d_bits, size=size,
            a_shr=a_shr, a_mac=a_mac, b_shr=b_shr, b_mac=b_mac,
            c_shr=c_shr, c_mac=c_mac,
            lzp_shr=lzp_shr, lzp_mac=lzp_mac, lz_shr=lz_shr, lz_mac=lz_mac,
            delta_x_pub=delta_x_pub, delta_y_pub=delta_y_pub,
            delta_a_semi=None, delta_b_semi=None,
            global_key_shr=global_key_shr,
            bytes_sent=bytes_sent,
            deltas_lock=deltas_lock, deltas_store=deltas_store,
        )

        # Publish result
        if isinstance(result, np.ndarray):
            result_list = [str(int(x)) for x in result]
        else:
            result_list = [str(x) for x in result]
        state.update(result=json.dumps(result_list), phase="done", status="Done")
        state.log("Protocol complete.", {"result": result_list})

        # Close network connection before looping
        try:
            net.close()
        except Exception:
            pass


if __name__ == "__main__":
    main()
